Resolve incremental compilation issue for Ceph project
Previously boost.tar.gz copy unconditionally to ceph src dir, and it
is considered source change and rebuild ceph project.
To improve, judge whether the tar file existed in src dir and only
copy when the file is not copy, this will not cause rebuild each time.

Change-Id: I943e54bee7249f6a771607efb4b679166c79ff9d
Signed-off-by: Chen, Tingjie <tingjie.chen@intel.com>

diff --git a/ceph/ceph/centos/build_srpm b/ceph/ceph/centos/build_srpm
--- a/ceph/ceph/centos/build_srpm
+++ b/ceph/ceph/centos/build_srpm
@@ -152,10 +152,12 @@ if [ ! -f "$BOOST_TAR" ]; then
 fi
 
 echo "ceph customization build_srpm : copy boost tar file from $BOOST_TAR to $SRC_DIR"
-cp $BOOST_TAR $SRC_DIR
-if [ $? -ne 0 ]; then
-    echo "ERROR: ceph customization build_srpm : copy $BOOST_TAR fails."
-    exit 1
+if [ ! -f "$SRC_DIR/$BOOST_TAR_FILE" ]; then
+    cp $BOOST_TAR $SRC_DIR
+    if [ $? -ne 0 ]; then
+        echo "ERROR: ceph customization build_srpm : copy $BOOST_TAR fails."
+        exit 1
+    fi
 fi
 
 temp_dir=$PWD
